### ISSUE TITLE
Fix also doccer file

### ISSUE THREAD

**Issue by aaltat** [F-Secure/flaky-tests-detection#19]
This is not correct: https://github.com/F-Secure/flaky-tests-detection/blob/master/Dockerfile#L3

**Comment by aaltat** [comment]
Also this is not correct: https://github.com/F-Secure/flaky-tests-detection/blob/master/entrypoint.sh

**Comment by oikarinen-fs** [comment]
Fixed in commit: https://github.com/F-Secure/flaky-tests-detection/commit/488214a947cd987d1e7d5ce6587a46fafa2bc0c4
