### ISSUE TITLE
Package in PyPi might be good idea too

### ISSUE THREAD

**Issue by tatu-aalto** [F-Secure/flaky-tests-detection#8]
Not all CI are in GitHub and creating package to Pypi would be also nice.

**Comment by matveypashkovskiy** [comment]
one of the problems with Docker approach is that [GitHub Actions cannot run docker on Win runners](https://github.com/actions/virtual-environments/issues/1143#issuecomment-651178811)

**Comment by matveypashkovskiy** [comment]
Two things are needed:
* semantic versioning in GitHub actions
* package publishing

as an example [pipeline](https://github.com/F-Secure/pytest-rts/blob/master/.github/workflows/pytest-rts.yml) from pytest-rts package could be used

**Comment by matveypashkovskiy** [comment]
Relevant files:
* [Commit Message Format in CONTRIBUTING.md](https://github.com/F-Secure/pytest-rts/blob/master/docs/CONTRIBUTING.md#-commit-message-format)
* [setup.py](https://github.com/F-Secure/pytest-rts/blob/master/setup.py)
* [Makefile](https://github.com/F-Secure/pytest-rts/blob/master/Makefile#L16)

**Comment by matveypashkovskiy** [comment]
BTW what would be the right name for the repo/package?
* `fliprate_actions`
* `fliprate-actions`
* or maybe we need better name like `flaky-tests-detection`, or something similar?

@tatu-aalto, @alexey-vyskubov, @oikarinen-fs?

**Comment by tatu-aalto** [comment]
When looking from Python code point of view, name with underscore is better. Based on famous gut feeling, `flaky_tests_detection` feels better because it describes what we are trying to achieve.

**Comment by matveypashkovskiy** [comment]
I think that is done now, @oikarinen-fs please reopen if there is still something to do.
